# Generated by Django 2.2.7 on 2019-11-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='linux',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('para1', models.CharField(default='', max_length=5000)),
                ('para2', models.CharField(default='', max_length=5000)),
                ('para3', models.CharField(default='', max_length=5000)),
                ('pub_date', models.DateField()),
                ('blog_pic', models.ImageField(default='', upload_to='blog_images')),
            ],
        ),
    ]
