# Generated by Django 2.2.7 on 2019-11-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linux', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='linux',
            new_name='linux_data',
        ),
    ]
