# Generated by Django 2.2.6 on 2019-11-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogspot',
            name='flags',
            field=models.CharField(default='', max_length=20),
        ),
    ]
