# Generated by Django 2.2 on 2019-12-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191126_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogspot',
            name='hint',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='blogspot',
            name='hint2',
            field=models.CharField(default='', max_length=200),
        ),
    ]
