# Generated by Django 2.2.7 on 2019-11-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blogspot_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogspot',
            name='cat',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='blogspot',
            name='flags',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='blogspot',
            name='habody',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='blogspot',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
