# Generated by Django 2.2.7 on 2019-11-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191120_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogspot',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
