# Generated by Django 2.2 on 2019-12-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191225_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogspot',
            name='serial',
            field=models.CharField(default='', max_length=10),
        ),
    ]
