# Generated by Django 2.2.7 on 2019-11-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_blogspot_is_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='exclusive',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='exclusive',
            name='points',
            field=models.CharField(default='', max_length=10),
        ),
    ]
