# Generated by Django 2.2 on 2019-12-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_blogspot_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogspot',
            name='points',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='exclusive',
            name='points',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
