# Generated by Django 2.2 on 2019-12-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191230_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='exclusive',
            name='is_normal',
            field=models.BooleanField(default=True),
        ),
    ]
