# Generated by Django 2.1 on 2020-01-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200101_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='exclusive',
            name='solvedctfid',
            field=models.CharField(default='', max_length=300),
        ),
    ]
