# Generated by Django 2.1 on 2020-01-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_exclusive_solvedctfid'),
    ]

    operations = [
        migrations.CreateModel(
            name='solvedctf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulkctf', models.ForeignKey(on_delete='Cascade', related_name='ctfids', to='main.exclusive')),
            ],
        ),
    ]
