# Generated by Django 2.2.6 on 2019-11-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buginfo',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=30)),
                ('scope_description', models.CharField(max_length=500)),
                ('scope_link', models.CharField(max_length=50)),
                ('outscope_description', models.CharField(max_length=500)),
                ('P1', models.CharField(max_length=50)),
                ('P2', models.CharField(max_length=50)),
                ('P3', models.CharField(max_length=50)),
                ('P4', models.CharField(max_length=50)),
                ('points', models.CharField(max_length=50)),
            ],
        ),
    ]
