# Generated by Django 2.2.7 on 2019-11-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about_game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=500)),
                ('about', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='game_regis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('year', models.CharField(max_length=90)),
                ('type', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
