# Generated by Django 2.1 on 2020-02-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('para1', models.CharField(default='', max_length=5000)),
                ('para2', models.CharField(default='', max_length=5000)),
                ('para3', models.CharField(default='', max_length=5000)),
                ('para4', models.CharField(default='', max_length=5000)),
                ('para5', models.CharField(default='', max_length=5000)),
                ('pub_date', models.DateField()),
                ('crypto_pic', models.ImageField(default='', upload_to='blog_images')),
            ],
        ),
    ]
